module.exports = {
	LOAD_KEYBOARD_LAYOUT: 'LOAD_KEYBOARD_LAYOUT',

	// keybinding-changer

	KEYBINDING_CHANGER_SET_VIEW: 'KEYBINDING_CHANGER_SET_VIEW',
	KEYBINDING_CHANGER_SET_DATA: 'KEYBINDING_CHANGER_SET_DATA',
	KEYBINDING_CHANGER_SAVE: 'KEYBINDING_CHANGER_SAVE',
	KEYBINDING_CHANGER_CLOSE: 'KEYBINDING_CHANGER_CLOSE',
	KEYBINDING_CHANGER_OPEN: 'KEYBINDING_CHANGER_OPEN',
	KEYBINDING_CHANGER_RESET: 'KEYBINDING_CHANGER_RESET',

	// error-dialog

	ERROR_DIALOG_CLOSE: 'ERROR_DIALOG_CLOSE',
	ERROR_DIALOG_OPEN: 'ERROR_DIALOG_OPEN',

	// preset

	PRESET_EXPORT: 'PRESET_EXPORT',
	PRESET_IMPORT: 'PRESET_IMPORT',
	PRESET_IMPORT_FILE: 'PRESET_IMPORT_FILE',
	PRESET_CHANGE_DESCRIPTION: 'PRESET_CHANGE_DESCRIPTION',
	PRESET_CHANGE_TITLE: 'PRESET_CHANGE_TITLE',

	// custom-code

	CUSTOM_CODE_UPDATE: 'CUSTOM_CODE_UPDATE',

	// load

	LOAD_PRESETS: 'LOAD_PRESETS',
	LOAD_PRESET: 'LOAD_PRESET',

	// other

	CHANGE: 'CHANGE',
	CHANGE_LAYOUT: 'CHANGE_LAYOUT',
	DOWNLOAD: 'DOWNLOAD',
	ACTIVATE_TAB: 'ACTIVATE_TAB',
	ADD_LAYOUT: 'ADD_LAYOUT',
	EXPORT_PRESET: 'EXPORT_PRESET',
	IMPORT_PRESET: 'IMPORT_PRESET',
	CHANGE_CHATWHEEL: 'CHANGE_CHATWHEEL',
	ADD_CHATWHEEL: 'ADD_CHATWHEEL',

	// settings
	CHANGE_SETTING: 'CHANGE_SETTING',
	REMAP_ALT_KEY: 'REMAP_ALT_KEY',

	// cycles
	CYCLE_ADD: 'CYCLE_ADD',
	CYCLE_MOVE_UP: 'CYCLE_MOVE_UP',
	CYCLE_MOVE_DOWN: 'CYCLE_MOVE_DOWN',
	CYCLE_REMOVE_ITEM: 'CYCLE_REMOVE_ITEM',
	CYCLE_ADD_ITEM: 'CYCLE_ADD_ITEM',

	// remove-dialog
	REMOVE_DIALOG_CONTINUE: 'REMOVE_DIALOG_CONTINUE',
	REMOVE_DIALOG_ABORT: 'REMOVE_DIALOG_ABORT',
	SHOW_REMOVE_DIALOG: 'SHOW_REMOVE_DIALOG'
};
