module.exports = {
    'CHANGE': 'CHANGE',
    'CHANGE_LAYOUT': 'CHANGE_LAYOUT',
    'CHANGE_BIND': 'CHANGE_BIND',
    'SAVE_BINDING': 'SAVE_BINDING',
    'CLOSE_CHANGER': 'CLOSE_CHANGER',
    'DOWNLOAD': 'DOWNLOAD',
    'ACTIVATE_TAB': 'ACTIVATE_TAB',
    'ADD_LAYOUT': 'ADD_LAYOUT',
    'EXPORT_PRESET': 'EXPORT_PRESET',
    'IMPORT_PRESET': 'IMPORT_PRESET',
    'CHANGE_CHATWHEEL': 'CHANGE_CHATWHEEL',
    'ADD_CHATWHEEL': 'ADD_CHATWHEEL',

    // settings
    'CHANGE_SETTING': 'CHANGE_SETTING',

    // cycles
    'CYCLE_ADD': 'CYCLE_ADD',
    'CYCLE_MOVE_UP': 'CYCLE_MOVE_UP',
    'CYCLE_MOVE_DOWN': 'CYCLE_MOVE_DOWN',
    'CYCLE_REMOVE_ITEM': 'CYCLE_REMOVE_ITEM',
    'CYCLE_ADD_ITEM': 'CYCLE_ADD_ITEM',

    // remove-dialog
    'REMOVE_DIALOG_CONTINUE': 'REMOVE_DIALOG_CONTINUE',
    'REMOVE_DIALOG_ABORT': 'REMOVE_DIALOG_ABORT',
    'SHOW_REMOVE_DIALOG': 'SHOW_REMOVE_DIALOG'
};
