module.exports = {
    'CHANGE': 'CHANGE',
    'CHANGE_LAYOUT': 'CHANGE_LAYOUT',
    'CHANGE_BIND': 'CHANGE_BIND',
    'SAVE_BINDING': 'SAVE_BINDING',
    'CLOSE_CHANGER': 'CLOSE_CHANGER',
    'DOWNLOAD': 'DOWNLOAD',
    'ACTIVATE_TAB': 'ACTIVATE_TAB',
    'REMOVE_CURRENT_LAYOUT': 'REMOVE_CURRENT_LAYOUT',
    'ADD_LAYOUT': 'ADD_LAYOUT'
};
