module.exports = {
    'CHANGE': 'CHANGE',
    'CHANGE_LAYOUT': 'CHANGE_LAYOUT',
    'CHANGE_BIND': 'CHANGE_BIND',
    'SAVE_BINDING': 'SAVE_BINDING',
    'CLOSE_CHANGER': 'CLOSE_CHANGER',
    'DOWNLOAD': 'DOWNLOAD',
    'ACTIVATE_TAB': 'ACTIVATE_TAB',
    'REMOVE_CURRENT_LAYOUT': 'REMOVE_CURRENT_LAYOUT',
    'ADD_LAYOUT': 'ADD_LAYOUT',
    'EXPORT_PRESET': 'EXPORT_PRESET',
    'IMPORT_PRESET': 'IMPORT_PRESET',
    'CHANGE_CHATWHEEL': 'CHANGE_CHATWHEEL',
    'ADD_CHATWHEEL': 'ADD_CHATWHEEL',
    'REMOVE_CHATWHEEL': 'REMOVE_CHATWHEEL',

    // settings
    'CHANGE_SETTING': 'CHANGE_SETTING',

    // cycles
    'CYCLE_ADD': 'CYCLE_ADD',
    'CYCLE_MOVE_UP': 'CYCLE_MOVE_UP',
    'CYCLE_MOVE_DOWN': 'CYCLE_MOVE_DOWN',
    'CYCLE_REMOVE_ITEM': 'CYCLE_REMOVE_ITEM',
    'CYCLE_ADD_ITEM': 'CYCLE_ADD_ITEM',
    'CYCLE_REMOVE': 'CYCLE_REMOVE'
};
